#A data deve ser editada dentro do formato pré-estabelecido, aconselho usar o dia imediatamente anterior ao início da rodada, tendo em vista que a versào atual do programa considera todos os jogos começando meia noite (exato início do dia), apesar dele jogar a informação certa de hora no forms (falta ajustar o horário de verão). O formato da data é ano, mês (sem o zero, abril é 4 e não 04), dia (sem o zero), hora, minutos.
# Inicio_Rodada: ['2022', '8', '19', '20', '30']
Inicio_Rodada: ['2022', '5', '1', '20', '30']


#Para o fim recomendo usar o dia imediatamente posterior, zerado na hora, podemos testar.
# Fim_Rodada: ['2022', '8', '23', '20', '30']
Fim_Rodada: ['2022', '5', '24', '20', '30']

#Sempre use a URL do schedule.
URL_FACS: https://www.worldfootball.net/all_matches/eng-fa-community-shield-2022/

URL_PL: https://www.worldfootball.net/all_matches/eng-premier-league-2022-2023/

URL_SPFL: https://sco.worldfootball.net/all_matches/sco-premiership-2022-2023/

URL_SPFL_CHAMPIONSHIP: https://sco.worldfootball.net/all_matches/sco-premiership-2023-championship/

URL_SPFL_RELEGATION: https://sco.worldfootball.net/all_matches/sco-premiership-2023-relegation/

URL_SPFL_PLAYOFFS: https://sco.worldfootball.net/all_matches/sco-playoff-2021-2022-premiership/

URL_LCH: https://sco.worldfootball.net/schedule/sco-championship-2022-2023-spieltag/36/

URL_LCH_PLAYOFFS: https://www.worldfootball.net/all_matches/eng-playoff-2021-2022-championship/
